"""Added StaffWeeklHours to keep track of how many hours staff worked in week

Revision ID: 021964661a70
Revises: 031d9e87bb4f
Create Date: 2026-08-26 00:32:59.492412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021964661a70'
down_revision: Union[str, Sequence[str], None] = '031d9e87bb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
