"""changed include field to deleted

Revision ID: 2782aa030fa8
Revises: cb3792243b74
Create Date: 2026-08-22 15:40:57.354283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2782aa030fa8'
down_revision: Union[str, Sequence[str], None] = 'cb3792243b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.drop_column('department', 'include')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('include', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('department', 'deleted')
    # ### end Alembic commands ###
