"""renamed weekly_hours to weekly_hours_worked for easy readbility

Revision ID: 87bd5edceae4
Revises: 5a2c67ab7d64
Create Date: 2026-08-26 01:24:25.162582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bd5edceae4'
down_revision: Union[str, Sequence[str], None] = '5a2c67ab7d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
