"""Modified age field

Revision ID: e1b4754e84a5
Revises: 9e635da63b54
Create Date: 2026-07-06 17:48:03.755722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1b4754e84a5'
down_revision: Union[str, Sequence[str], None] = '9e635da63b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
