"""added unique constraint to department

Revision ID: 4c4a501a2ce6
Revises: ce8758b0963c
Create Date: 2026-09-02 19:09:36.005826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4a501a2ce6'
down_revision: Union[str, Sequence[str], None] = 'ce8758b0963c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'department', ['name', 'creator_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='unique')
    # ### end Alembic commands ###
