"""Added deleted field to Staff

Revision ID: 5efb4884906a
Revises: 2782aa030fa8
Create Date: 2026-08-23 19:02:01.909627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efb4884906a'
down_revision: Union[str, Sequence[str], None] = '2782aa030fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'deleted')
    # ### end Alembic commands ###
