"""Added age

Revision ID: 9e635da63b54
Revises: b0f295d5733c
Create Date: 2026-07-06 08:05:07.016415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e635da63b54'
down_revision: Union[str, Sequence[str], None] = 'b0f295d5733c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('age', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'staff', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'age')
    # ### end Alembic commands ###
