"""added default value to hours in StaffWeeklyHoirs

Revision ID: a7d1ef7f4457
Revises: 87bd5edceae4
Create Date: 2026-08-26 02:09:05.622296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d1ef7f4457'
down_revision: Union[str, Sequence[str], None] = '87bd5edceae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
