"""Made Email field Unique

Revision ID: b0f295d5733c
Revises: de2166db2e51
Create Date: 2026-07-06 07:58:38.703066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0f295d5733c'
down_revision: Union[str, Sequence[str], None] = 'de2166db2e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduleweek')
    op.drop_index(op.f('name'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_staff_position'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('exclusion')
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_date', sa.DATE(), nullable=False),
    sa.Column('week_day', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('time', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('schedule_ibfk_3')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('schedule_ibfk_2')),
    sa.ForeignKeyConstraint(['week_id'], ['scheduleweek.id'], name=op.f('schedule_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exclusion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('shift', 'day'), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('exclusion_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contract_hours', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_staff_position'), 'staff', ['position'], unique=False)
    op.create_table('department',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('min_staff', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_staff', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('include', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'department', ['name'], unique=True)
    op.create_table('scheduleweek',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.DATE(), nullable=False),
    sa.Column('week_end', sa.DATE(), nullable=False),
    sa.Column('complete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
