"""modified min_staff, max_staff, contract_hours and name in staff model

Revision ID: b14d93a2677e
Revises: d57669ceb834
Create Date: 2026-09-04 06:46:38.213656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14d93a2677e'
down_revision: Union[str, Sequence[str], None] = 'd57669ceb834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
