"""Added generated_at field to ScheduleWeek

Revision ID: 031d9e87bb4f
Revises: 5efb4884906a
Create Date: 2026-08-24 18:33:30.906706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031d9e87bb4f'
down_revision: Union[str, Sequence[str], None] = '5efb4884906a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduleweek', sa.Column('generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduleweek', 'generated_at')
    # ### end Alembic commands ###
