"""added relationship between Schedule week and User and WeeklyHoursWorked and User

Revision ID: 3e098017ee9a
Revises: b14d93a2677e
Create Date: 2026-09-04 10:42:35.055762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e098017ee9a'
down_revision: Union[str, Sequence[str], None] = 'b14d93a2677e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        UPDATE staffweeklyhours sw
        LEFT JOIN user u ON sw.creator_id = u.id
        SET sw.creator_id = NULL
        WHERE sw.creator_id IS NOT NULL
          AND u.id IS NULL
    """)
    
    op.execute("""
        UPDATE scheduleweek sw
        LEFT JOIN user u ON sw.creator_id = u.id
        SET sw.creator_id = NULL
        WHERE sw.creator_id IS NOT NULL
          AND u.id IS NULL
    """)
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'staffweeklyhours', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staffweeklyhours', type_='foreignkey')
    # ### end Alembic commands ###
