"""Checkpoint -> confirming database tables

Revision ID: 4016b5c9268d
Revises: 3e098017ee9a
Create Date: 2026-09-05 00:32:46.283264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4016b5c9268d"
down_revision: Union[str, Sequence[str], None] = "3e098017ee9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "staffweeklyhours", sa.Column("creator_id", sa.Integer(), nullable=True)
    )

    op.create_foreign_key(None, "staffweeklyhours", "user", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
