"""added min_hours to staff

Revision ID: cb3792243b74
Revises: 2e5b24f3a78b
Create Date: 2026-07-22 00:06:24.229899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3792243b74'
down_revision: Union[str, Sequence[str], None] = '2e5b24f3a78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('min_hours', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'min_hours')
    # ### end Alembic commands ###
