"""added user field and createdrelationships

Revision ID: ce8758b0963c
Revises: 6f33b2e8c50d
Create Date: 2026-09-02 18:35:13.254084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8758b0963c'
down_revision: Union[str, Sequence[str], None] = '6f33b2e8c50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'department', 'user', ['creator_id'], ['id'])
    op.add_column('schedule', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule', 'user', ['creator_id'], ['id'])
    op.add_column('staff', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'creator_id')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'creator_id')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'creator_id')
    # ### end Alembic commands ###
