"""removed unique department name

Revision ID: d57669ceb834
Revises: 4c4a501a2ce6
Create Date: 2026-09-02 19:12:44.910929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57669ceb834'
down_revision: Union[str, Sequence[str], None] = '4c4a501a2ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('name'), 'department', ['name'], unique=True)
    # ### end Alembic commands ###
